feat[STOCK-50]
vladdossik/lissa-trading-moex-api-service pull request #1
Opened 2024-11-30 08:52 UTC by Blaskowitz14

Добавлены 5 эндпоинтов повторяющих функционал tinkoff-api-service.

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/client/IssMoexClient.java
> +                        .path(String.format("/engines/stock/markets/shares/boards/TQBR/securities/%s/candles.json",
Вынести в ямл

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/client/IssMoexClient.java
> +                        .path(String.format("/engines/stock/markets/shares/boards/TQBR/securities/%s.json", ticker))
Вынести в ямл

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/candle/CandleDto.java
> +    private Long volume;
Поля без аннотации вроде как пишем без пробелов, все подряд
А те что с аннотациями в конце добавь с пробелами

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/candle/CandleListDto.java
> +
Также во всех дтошках убери постые строки

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/moex/Content.java
> +public class Content {
ContentDto?

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/stock/StockDto.java
> +
Аналогично

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/stock/StockPriceDto.java
> +
Аналогично

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/candle/CandleAggregatorImpl.java
> +
@override?

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/candle/CandleAggregatorImpl.java
> +    public List<CandleDto> aggregate(List<CandleDto> candleDtoList,
Какой то длинный метод, может можно что то вынести

2024-11-30 10:56 UTC, SashaTyutyaev commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/candle/CandleAggregator.java
> +    public List<CandleDto> aggregate(List<CandleDto> candles, CandleIntervalEnum interval);
В интерфейсах же не ставим видимость

2024-12-01 12:44 UTC, vladdossik commented on .gitattributes
> +/mvnw text eol=lf
эт че такое?

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/client/IssMoexClient.java
> +                        .path(String.format("/engines/stock/markets/shares/boards/TQBR/securities/%s.json", ticker))
скорее в константы
хосты - йамл
урлы - код

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/client/IssMoexClient.java
> +                        .path(String.format("/engines/stock/markets/shares/boards/TQBR/securities/%s/candles.json",
в константы

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/candle/CandleDto.java
> +    private Long volume;
таки да

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/moex/ContentValidator.java
> +        if (content == null || content.getData().isEmpty()) {
+ добавить || content.getData() == null

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/dto/moex/ContentValidator.java
> +        if (content == null || content.getData().isEmpty()) {
или вообще content == null || CollectionUtils.isEmpty(content.getData())

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/ContentMapper.java
> +    public <T>T ContentToPojo(Content content, Class<T> clazz) {
почему с большой буквы метод называется?

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/candle/CandleAggregator.java
> +    public List<CandleDto> aggregate(List<CandleDto> candles, CandleIntervalEnum interval);
так точно

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/candle/CandleAggregatorImpl.java
> +    public List<CandleDto> aggregate(List<CandleDto> candleDtoList,
ох бля да

2024-12-01 12:44 UTC, vladdossik commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/stock/StockServiceImpl.java
> +           stockDtoList.add(stockDto);
ну как будто можно было в 1 строку просто написать и все

2024-12-01 13:19 UTC, kenpxrk1 requested changes

2024-12-01 13:19 UTC, kenpxrk1 commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/ContentMapper.java
> +public class ContentMapper {
Мне вообще не нравится нейминг в методах, мы называем их TypeToType, а не TypeToPojo

2024-12-01 13:19 UTC, kenpxrk1 commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/ServiceConstants.java
> +public class ServiceConstants {
соблюдай единый порядок модификаторов

2024-12-01 13:19 UTC, kenpxrk1 commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/candle/CandleServiceImpl.java
> +public class CandleServiceImpl implements CandleService {
в Тинькофф сервисе мы не разделяем свечи и акции ибо это непосредственно друг к другу относится, я бы пихнул все в стоксервис

2024-12-01 13:19 UTC, kenpxrk1 commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/ServiceConstants.java
> +public class ServiceConstants {
и как будто выносить в отдельный класс константы так себе идея, ибо мы везде пишем константы в поля класса где они используются и со временем вероятно в твой класс их писать никто не будет, поэтому я бы раскидал их по классам, тем более твой класс с константами не находится в нейм спейсе сервисов и их приходиться статически импортировать

2024-12-01 13:19 UTC, kenpxrk1 commented on src/main/java/ru/blaskowitz/lissatradingmoexapiservice/service/stock/StockServiceImpl.java
> +        List<String> companyNamesList  = new ArrayList<>();
можно написать List<String> list = getStocks(...).toList() и будет красивше

2024-12-01 13:19 UTC, kenpxrk1 commented on pom.xml
> +        <version>3.3.6</version>
мы юзаем 3.3.4 но не критично я думаю

2024-12-01 14:00 UTC, kenpxrk1 commented on pom.xml
> +    <groupId>ru.blaskowitz</groupId>
тут тоже поменять

2024-12-03 06:25 UTC, vladdossik commented on pom.xml
> +        <version>3.3.6</version>
критично в большой компании будет
тут закроем глаза
но заполнить стоит

2024-12-03 06:25 UTC, vladdossik commented on pom.xml
> +    <scm>
вообще пустые блоки
нужно убрать

2024-12-03 06:25 UTC, vladdossik commented on src/main/java/lissa/trading/moexapi/service/client/IssMoexClient.java
> +    private final static String getCandleListUrl = "/engines/stock/markets/" +
эти урлы - константы
должны называться как GET_CANDLE_LIST_URL

2024-12-03 06:25 UTC, vladdossik commented on src/main/java/lissa/trading/moexapi/service/dto/moex/ContentDto.java
> +    public ContentDto() {
по идее ты можешь просто добавить @NoArgsConstructor, а у полей дописать = new ArrayList();

по идее будет работать точно также

не крит ни разу

2024-12-03 06:25 UTC, vladdossik commented on src/main/java/lissa/trading/moexapi/service/dto/stock/StockDto.java
> +    @JsonProperty("ticker")
то есть у них какие-то поля с большой буквы, а какие-то с маленькой?

2024-12-03 12:46 UTC, vladdossik approved these changes

2024-12-04 15:35 UTC, kenpxrk1 approved these changes

2024-12-05 08:08 UTC, merged